kind: pipeline
name: default

steps:
  - name: linter
    image: snakepacker/python:all
    commands:
      - tox -e lint

  - name: python 3.5
    image: snakepacker/python:all
    commands:
      - tox -e py35

  - name: python 3.6
    image: snakepacker/python:all
    commands:
      - tox -e py36

  - name: python 3.7
    image: snakepacker/python:all
    commands:
      - tox -e py37

  - name: python 3.8
    image: snakepacker/python:all
    commands:
      - tox -e py38

  - name: python 3.9
    image: snakepacker/python:all
    commands:
      - tox -e py39
